services:
  - type: web
    name: sonus
    env: node
    region: oregon
    plan: free
    buildCommand: "npm ci --include=dev && npm run build"
    startCommand: "npm ci && npm start"
    healthCheckPath: "/"
